apiVersion: v1
kind: Service
metadata:
  name: coffeeandit-ci
  labels:
    app: coffeeandit-ci
    service: coffeeandit-ci
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: coffeeandit-ci

---
apiVersion: v1
kind: Service
metadata:
  name: coffeeandit-ci-svc-lb
  labels:
    app: coffeeandit-ci-svc-lb
    service: coffeeandit-ci-svc-lb
spec:
  ports:
    - port: 80
      name: http
      targetPort: 8080
  type: LoadBalancer

  selector:
    app: coffeeandit-ci
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeeandit-ci
  labels:
    app: coffeeandit-ci
spec:
  selector:
    matchLabels:
      app: coffeeandit-ci
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: coffeeandit-ci
    spec:
      containers:
        - name: coffeeandit-ci
          image: 049389827536.dkr.ecr.us-east-2.amazonaws.com/coffeeandit-ci:e82aabf70a8a757dcf35ca9c7e1e5cc78624f85
          env:
            - name : SPRING_PROFILES_ACTIVE
              value: "prd"
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
